# Generated by Django 5.0 on 2025-02-28 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0004_remove_activityrequirement_knowledge_path_and_more'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='quiz',
        #     name='activity_requirement',
        # ),
        migrations.AddField(
            model_name='quiz',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.node'),
            preserve_default=False,
        ),
    ]
