# Generated by Django 5.0 on 2025-02-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0005_delete_activityrequirement_and_more'),
        ('quizzes', '0002_remove_quiz_activity_requirement_quiz_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='knowledge_paths.node'),
        ),
    ]
