# Generated by Django 5.0 on 2025-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed per day'),
        ),
    ]
