# Generated by Django 5.0 on 2025-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_max_attempts_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts_per_day',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1, help_text='Maximum number of attempts allowed per day (1-9)'),
        ),
    ]
