# Generated by Django 5.0 on 2025-03-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_max_attempts_per_day'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE quizzes_quiz DROP COLUMN activity_requirement_id;',
            reverse_sql='ALTER TABLE quizzes_quiz ADD COLUMN activity_requirement_id bigint;'
        ),
    ]
