# Generated by Django 5.0 on 2025-03-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_fix_activity_requirement_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts_per_day',
            field=models.SmallIntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=2, help_text='Maximum number of attempts allowed per day (2-9)'),
        ),
    ]
