# Generated by Django 5.0 on 2026-01-29 20:06

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        ('knowledge_paths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('thumbnail', models.FileField(blank=True, help_text='Cryptocurrency logo/thumbnail (supports JPG, PNG, GIF, SVG)', null=True, upload_to=profiles.models.upload_crypto_thumbnail, validators=[profiles.models.validate_image_or_svg_file])),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('url_link', models.CharField(blank=True, max_length=250)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crypto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(blank=True, max_length=250)),
                ('profile_description', models.TextField(blank=True, max_length=2500)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('timezone', models.CharField(blank=True, max_length=30)),
                ('is_teacher', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_profile_picture)),
                ('total_points', models.IntegerField(default=0, help_text='Total gamification points earned by the user')),
                ('featured_badge', models.ForeignKey(blank=True, help_text='Badge destacado que se muestra junto al nombre de usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_profiles', to='gamification.userbadge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Sugerencia o feedback del usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNodeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.knowledgepath')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'knowledge_path', 'node')},
            },
        ),
    ]
