# Generated by Django 5.0 on 2025-02-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0003_node_description'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogressknowledgepath',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='userprogressknowledgepath',
            name='knowledge_path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.knowledgepath'),
            preserve_default=False,
        ),
    ]
