# Generated by Django 5.0 on 2025-02-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitystatus',
            name='activity_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.activityrequirement'),
        ),
        migrations.AlterField(
            model_name='userprogressknowledgepath',
            name='node_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.nodeorder'),
        ),
    ]
