# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_change_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times the user has changed their username (max 2)'),
        ),
    ]
