# Generated by Django 5.0 on 2025-02-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_useractivitystatus_activity_requirement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogressknowledgepath',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprogressknowledgepath',
            name='node_order',
        ),
    ]
