# Generated by Django 5.0 on 2025-06-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivityStatus',
        ),
    ]
