# Generated by Django 5.0 on 2025-02-26 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0003_node_description'),
        ('profiles', '0002_remove_userprogressknowledgepath_is_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNodeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.knowledgepath')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'knowledge_path', 'node')},
            },
        ),
    ]
