# Generated by Django 5.0 on 2026-03-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_username_change_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='Optional source tag (e.g. landing, footer)', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
