# Generated by Django 5.0 on 2025-07-07 16:40

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_useractivitystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Cryptocurrency logo/thumbnail', null=True, upload_to=profiles.models.upload_crypto_thumbnail),
        ),
    ]
