# Generated by Django 5.0 on 2025-02-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_usernodecompletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgressKnowledgePath',
        ),
    ]
