# Generated by Django 5.0 on 2025-02-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_delete_userprogressknowledgepath'),
    ]

    operations = [
        #         migrations.RemoveField(
        #             model_name='useractivitystatus',
        #             name='activity_requirement',
        #         ),
    ]
