# Generated by Django 5.0 on 2025-07-07 17:02

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_cryptocurrency_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Cryptocurrency logo/thumbnail (supports JPG, PNG, GIF, SVG)', null=True, upload_to=profiles.models.upload_crypto_thumbnail, validators=[profiles.models.validate_image_or_svg_file]),
        ),
    ]
