# Generated by Django 5.0 on 2025-03-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userquizcompletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuizCompletion',
        ),
    ]
