# Generated by Django 5.0 on 2026-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_token_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token_balance',
            field=models.PositiveIntegerField(default=0, help_text='Cached platform token balance. Mutate only via credit/debit_platform_tokens.'),
        ),
    ]
