# Generated by Django 5.0 on 2025-06-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_alter_bookmark_unique_together_bookmark_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='notes',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
