# Generated by Django 5.0 on 2026-07-13 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0023_topic_moderators_blank'),
        ('events', '0002_event_is_visible'),
        ('knowledge_paths', '0003_knowledgepath_image_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_club_covers/')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_book_clubs', to=settings.AUTH_USER_MODEL)),
                ('knowledge_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_clubs', to='knowledge_paths.knowledgepath')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_clubs', to='content.topic')),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_events', to='book_clubs.bookclub')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_club_links', to='events.event')),
            ],
            options={
                'ordering': ['event__date_start', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('book_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='book_clubs.bookclub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The discussion question text.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_questions', to='book_clubs.bookclub')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discussion_questions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Optional live session this question opens after.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_questions', to='events.event')),
                ('node', models.ForeignKey(blank=True, help_text='Mission this question follows (e.g. after Mission 1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_questions', to='knowledge_paths.node')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookclub',
            index=models.Index(fields=['slug'], name='book_clubs__slug_ddb74f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookclub',
            index=models.Index(fields=['status'], name='book_clubs__status_6647f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookclubevent',
            unique_together={('book_club', 'event')},
        ),
        migrations.AddIndex(
            model_name='bookclubmembership',
            index=models.Index(fields=['book_club', 'user'], name='book_clubs__book_cl_d45f4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookclubmembership',
            unique_together={('book_club', 'user')},
        ),
        migrations.AddIndex(
            model_name='discussionquestion',
            index=models.Index(fields=['book_club', 'status'], name='book_clubs__book_cl_0b075b_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionquestion',
            index=models.Index(fields=['opens_at'], name='book_clubs__opens_a_46a3f7_idx'),
        ),
    ]
