# Generated by Django 5.0 on 2026-07-18 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0004_bookclubmembership_introduction'),
        ('content', '0024_topic_activity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='topic',
            field=models.ForeignKey(
                blank=True,
                help_text='Tema de Investigación: timeline y biblioteca de media en el hub.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='book_clubs',
                to='content.topic',
            ),
        ),
    ]
