# Generated by Django 5.0 on 2026-09-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_clubs', '0007_bookclubmissionrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclubmissionrelease',
            name='opens_at',
            field=models.DateTimeField(blank=True, help_text='Null (or missing row) keeps the mission open. Set a future date to lock it until then.', null=True),
        ),
    ]
