"""
Django settings for academia_blockchain project.
Generated by 'django-admin startproject' using Django 3.0.4.
"""

import ast
import os
import dj_database_url
import logging
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Ensure logs directory exists even when /app is volume-mounted
LOGS_DIR = os.path.join(BASE_DIR, "logs")
try:
    os.makedirs(LOGS_DIR, exist_ok=True)
except Exception:
    # Fallback to tmp if repo mount prevents creating /app/logs
    LOGS_DIR = "/tmp/academia_blockchain_logs"
    os.makedirs(LOGS_DIR, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get("ACADEMIA_BLOCKCHAIN_SKEY", 'django-insecure-development-key-123')  # Default key for development
ENVIRONMENT = os.getenv("ENVIRONMENT", "DEVELOPMENT")

# Security settings based on environment
if ENVIRONMENT == "PRODUCTION":
    DEBUG = os.getenv("DEBUG", "False").lower() == "true"
    # Parse ALLOWED_HOSTS from environment variable (comma-separated)
    allowed_hosts_str = os.getenv("ALLOWED_HOSTS", "")
    if allowed_hosts_str:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(",") if host.strip()]
    else:
        raise ValueError("ALLOWED_HOSTS must be set in production environment!")
    
    # Security validation
    if DEBUG:
        raise ValueError("DEBUG must be False in production environment!")
    if SECRET_KEY == 'django-insecure-development-key-123':
        raise ValueError("Please set a proper SECRET_KEY in production!")
else:
    # Development defaults
    DEBUG = os.getenv("DEBUG", "True").lower() == "true"
    allowed_hosts_str = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0")
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(",") if host.strip()] if allowed_hosts_str else ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'profiles',
    'events',
    'content',
    'certificates',
    'comments',
    'quizzes',
    'votes',
    'knowledge_paths',
    'gamification',
    'search',
    'user_messages',
    'corsheaders',
    'storages',
    'rest_framework',
    'rest_framework.authtoken',  # Required for dj-rest-auth
    'dj_rest_auth',  # Add dj-rest-auth
    'dj_rest_auth.registration',  # Add registration support
    'rest_framework_simplejwt',
    'drf_yasg',
    'bookmarks',
    'notifications'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'utils.logging_middleware.RequestLoggingMiddleware',
]

# CORS settings: use explicit origins; never Allow All in production.
CORS_ALLOW_CREDENTIALS = True
_CORS_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://sophia-ai.algobeat.com",
    "https://sophia-ai-api.algobeat.com",
]
if ENVIRONMENT == "PRODUCTION":
    CORS_ALLOW_ALL_ORIGINS = False
    extra = os.getenv("CORS_ALLOWED_ORIGINS", "")
    CORS_ALLOWED_ORIGINS = _CORS_ORIGINS + [x.strip() for x in extra.split(",") if x.strip()]
    CORS_ALLOWED_ORIGIN_REGEXES = []  # No regex in production; use CORS_ALLOWED_ORIGINS only.
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _CORS_ORIGINS
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:[0-9]+$",
        r"^http://127.0.0.1:[0-9]+$",
    ]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://sophia-ai.algobeat.com",
    "https://sophia-ai-api.algobeat.com",
]
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read the CSRF cookie
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

# Session settings
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Security settings
# SECURE_CROSS_ORIGIN_OPENER_POLICY = None avoids strict COOP headers that break
# OAuth popups / cross-origin flows (e.g. Google login). Revisit if COOP is required.
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

ROOT_URLCONF = 'academia_blockchain.urls'

# To customize django-allauth templates: https://docs.allauth.org/en/latest/common/templates.html
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export'
            ],
        },
    },
]

# Only non-sensitive config is exported to templates (e.g. frontend CSRF token).
SETTINGS_EXPORT = [
    'CSRF_COOKIE_NAME',
]

WSGI_APPLICATION = 'academia_blockchain.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

#
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Logging
import json
from datetime import datetime

# Environment-specific logging configuration
if ENVIRONMENT == "PRODUCTION":
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
            "simple": {
                "format": "%(levelname)s %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
                "stream": "ext://sys.stdout",
            },
            "file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(LOGS_DIR, "academia_blockchain.log"),
                "maxBytes": 10485760,  # 10MB
                "backupCount": 5,
                "formatter": "verbose",
            },
            "error_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(LOGS_DIR, "errors.log"),
                "maxBytes": 10485760,  # 10MB
                "backupCount": 5,
                "formatter": "verbose",
                "level": "ERROR",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "django.request": {
                "handlers": ["console", "file", "error_file"],
                "level": "INFO",
                "propagate": False,
            },
            "django.security": {
                "handlers": ["console", "file", "error_file"],
                "level": "WARNING",
                "propagate": False,
            },
            "academia_blockchain": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "profiles": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "events": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "content": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "certificates": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "comments": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "quizzes": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "votes": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "knowledge_paths": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "search": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "user_messages": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "bookmarks": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "notifications": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "blockchain": {
                "handlers": ["console", "file", "error_file"],
                "level": "INFO",
                "propagate": False,
            },
            "auth": {
                "handlers": ["console", "file", "error_file"],
                "level": "INFO",
                "propagate": False,
            },
            "api": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
        },
        "root": {
            "handlers": ["console", "file"],
            "level": "WARNING",
        },
    }
else:
    # Development/Staging logging configuration
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
            "simple": {
                "format": "%(levelname)s %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
                "stream": "ext://sys.stdout",
            },
            "file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(LOGS_DIR, "academia_blockchain.log"),
                "maxBytes": 10485760,  # 10MB
                "backupCount": 3,
                "formatter": "verbose",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console", "file"],
                "level": "INFO",
                "propagate": False,
            },
            "django.request": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "academia_blockchain": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "profiles": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "events": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "content": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "certificates": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "comments": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "quizzes": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "votes": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "knowledge_paths": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "search": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "user_messages": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "bookmarks": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "notifications": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "blockchain": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "auth": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
            "api": {
                "handlers": ["console", "file"],
                "level": "DEBUG",
                "propagate": False,
            },
        },
        "root": {
            "handlers": ["console", "file"],
            "level": "INFO",
        },
    }

# REST Framework configuration
# Default deny: views must explicitly use AllowAny for public endpoints (login, register, search, health).
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Secure cookies in production when using HTTPS (recommended).
_USE_SECURE_COOKIES = ENVIRONMENT == "PRODUCTION" and os.getenv("USE_HTTPS", "true").lower() == "true"

# dj-rest-auth settings
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'acbc_jwt',
    'JWT_AUTH_REFRESH_COOKIE': 'acbc_refresh_token',
    'JWT_AUTH_HTTPONLY': True,
    'JWT_AUTH_SAMESITE': 'Lax',
    'JWT_AUTH_SECURE': _USE_SECURE_COOKIES,
    'TOKEN_MODEL': None,  # We're using JWT, not token authentication
}

# Allauth settings (already present, but adding some additional settings)
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'Academia Blockchain - '

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # 15 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),    # 30 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'AUTH_COOKIE': 'acbc_jwt',
    'REFRESH_COOKIE': 'acbc_refresh_token',
    'AUTH_COOKIE_SECURE': _USE_SECURE_COOKIES,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': '/',
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_OAUTH_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_OAUTH_SECRET_KEY'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

# Other config
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "profiles:set_jwt_token"
LOGOUT_REDIRECT_URL = "http://localhost:5173/profiles/login"
LANGUAGE_CODE = "en-us"
SEND_EMAILS = False
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = False
SITE_ID = 1  # django-allauth

# Email configuration
MAILGUN_DOMAIN = os.getenv('MAILGUN_DOMAIN', '')
MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY', '')
EMAIL_FROM = os.getenv('EMAIL_FROM', 'academiablockchain@no-reply.com')
EMAIL_FROM_NAME = os.getenv('EMAIL_FROM_NAME', 'Academia Blockchain')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', '')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))  # Timeout in seconds
EMAIL_MAX_RETRIES = int(os.getenv('EMAIL_MAX_RETRIES', '3'))

# Validate email configuration in production
if ENVIRONMENT == "PRODUCTION" and SEND_EMAILS:
    if not MAILGUN_DOMAIN or not MAILGUN_API_KEY:
        raise ValueError(
            "MAILGUN_DOMAIN and MAILGUN_API_KEY must be set in production when SEND_EMAILS=True"
        )

if ENVIRONMENT == "PRODUCTION":

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "ACADEMIA_BLOCKCHAIN_DB"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "any_password"),
            "HOST": os.getenv("DB_HOST", "postgres"),  # Use DB_HOST environment variable
            "PORT": "5432",
        }
    }

    # AWS config
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = 'academiablockchain'
    AWS_S3_REGION_NAME = 'us-west-2'  # example region
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

    AWS_S3_URL_PROTOCOL = 'https'
    AWS_S3_USE_SSL = True
    AWS_S3_VERIFY = True

    # STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    # MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    # DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR + "/media/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATIC_URL = "/static/"
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "ACADEMIA_BLOCKCHAIN_DB"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "any_password"),
            "HOST": os.getenv("DB_HOST", "postgres"),  # Use DB_HOST environment variable
            "PORT": "5432",
        }
    }

    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR + "/media/"
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# WhiteNoise configuration for serving static files in production
# WhiteNoise allows Django to serve static files even when DEBUG=False
# This is configured via middleware, but we can add storage settings for optimization
if ENVIRONMENT == "PRODUCTION":
    # Use WhiteNoise's compressed storage (without manifest to avoid missing file errors)
    # CompressedStaticFilesStorage compresses files but doesn't require manifest
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
