# Generated by Django 5.0 on 2026-07-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_visible'),
        ('knowledge_paths', '0005_sell_knowledge_paths'),
        ('payments', '0002_alter_cryptopayment_pay_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptopayment',
            old_name='registration',
            new_name='event_registration',
        ),
        migrations.AlterField(
            model_name='cryptopayment',
            name='event_registration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='crypto_payments',
                to='events.eventregistration',
            ),
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='path_purchase',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='crypto_payments',
                to='knowledge_paths.knowledgepathpurchase',
            ),
        ),
        migrations.AddConstraint(
            model_name='cryptopayment',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('event_registration__isnull', False), ('path_purchase__isnull', True)),
                    models.Q(('event_registration__isnull', True), ('path_purchase__isnull', False)),
                    _connector='OR',
                ),
                name='cryptopayment_exactly_one_target',
            ),
        ),
    ]
