# Generated by Django 5.0 on 2026-09-10 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_rename_topic_bch_direct_enabled_to_sales_enabled'),
        ('payments', '0008_platform_token_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenledgerentry',
            name='anchor_request',
            field=models.ForeignKey(blank=True, help_text='Set when reason=spend for a paid Bitcoin anchor request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_ledger_entries', to='content.transcriptanchorrequest'),
        ),
        migrations.AddConstraint(
            model_name='tokenledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'spend'), ('anchor_request__isnull', False)), fields=('anchor_request',), name='unique_token_anchor_request_spend'),
        ),
    ]
