# Generated by Django 5.0 on 2026-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_token_ledger_anchor_request_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bchdirectpayment',
            name='expected_amount_sats',
            field=models.BigIntegerField(help_text='Target amount in satoshis; verify allows BCH_AMOUNT_TOLERANCE_USD variance.'),
        ),
    ]
