# Generated by Django 5.0 on 2026-10-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_unlimited_consultation_user'),
        ('events', '0002_event_is_visible'),
        ('knowledge_paths', '0009_knowledge_path_snapshot_bitcoin_anchor'),
        ('payments', '0017_course_title_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayphonePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_transaction_id', models.CharField(max_length=64, unique=True)),
                ('payphone_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('transaction_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('amount_cents', models.PositiveIntegerField(help_text='Total charged in USD cents.')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reference', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('pay_with_card_url', models.URLField(blank=True, default='', max_length=512)),
                ('pay_with_payphone_url', models.URLField(blank=True, default='', max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('confirm_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payphone_payments', to='content.transcriptanchorrequest')),
                ('course_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payphone_payments', to='payments.coursepurchase')),
                ('event_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payphone_payments', to='events.eventregistration')),
                ('path_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payphone_payments', to='knowledge_paths.knowledgepathpurchase')),
                ('token_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payphone_payments', to='payments.tokenpurchase')),
                ('topic_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payphone_payments', to='content.topicpurchase')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='payphone_status_exp_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payphonepayment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('anchor_request__isnull', True), ('course_purchase__isnull', True), ('event_registration__isnull', False), ('path_purchase__isnull', True), ('token_purchase__isnull', True), ('topic_purchase__isnull', True)), models.Q(('anchor_request__isnull', True), ('course_purchase__isnull', True), ('event_registration__isnull', True), ('path_purchase__isnull', False), ('token_purchase__isnull', True), ('topic_purchase__isnull', True)), models.Q(('anchor_request__isnull', True), ('course_purchase__isnull', True), ('event_registration__isnull', True), ('path_purchase__isnull', True), ('token_purchase__isnull', True), ('topic_purchase__isnull', False)), models.Q(('anchor_request__isnull', False), ('course_purchase__isnull', True), ('event_registration__isnull', True), ('path_purchase__isnull', True), ('token_purchase__isnull', True), ('topic_purchase__isnull', True)), models.Q(('anchor_request__isnull', True), ('course_purchase__isnull', True), ('event_registration__isnull', True), ('path_purchase__isnull', True), ('token_purchase__isnull', False), ('topic_purchase__isnull', True)), models.Q(('anchor_request__isnull', True), ('course_purchase__isnull', False), ('event_registration__isnull', True), ('path_purchase__isnull', True), ('token_purchase__isnull', True), ('topic_purchase__isnull', True)), _connector='OR'), name='payphonepayment_exactly_one_target'),
        ),
    ]
