# Generated by Django 5.0 on 2026-01-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='badge',
            new_name='gamificatio_code_edd252_idx',
            old_name='gamificatio_code_idx',
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='gamificatio_is_acti_972de6_idx',
            old_name='gamificatio_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='gamificatio_user_id_2146ba_idx',
            old_name='gamificatio_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='gamificatio_earned__4b40a8_idx',
            old_name='gamificatio_earned__idx',
        ),
    ]
