# Generated by Django 5.0 on 2026-01-29 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('knowledge_paths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template_file', models.FileField(blank=True, null=True, upload_to='certificate_templates/')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, help_text='Optional note from the approver', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is REJECTED', null=True)),
                ('notes', models.JSONField(default=dict, help_text='Additional request-specific data')),
                ('event', models.ForeignKey(blank=True, help_text='Event for which certificate is requested', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('knowledge_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.knowledgepath')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requester', 'event'), ('requester', 'knowledge_path')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('blockchain_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255, null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Generated certificate file (PDF, etc.)', null=True, upload_to='certificates/')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes from the certificate issuer')),
                ('data', models.JSONField(default=dict, help_text='Additional certificate-specific data')),
                ('event', models.ForeignKey(blank=True, help_text='Event for which this certificate was issued', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('event_registration', models.ForeignKey(blank=True, help_text='Event registration associated with this certificate', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventregistration')),
                ('issued_by', models.ForeignKey(blank=True, help_text='User who issued the certificate (usually event creator or knowledge path author)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('knowledge_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.knowledgepath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetemplate')),
            ],
            options={
                'unique_together': {('user', 'event'), ('user', 'knowledge_path')},
            },
        ),
    ]
