# Generated by Django 5.0 on 2025-06-06 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='data',
            field=models.JSONField(default=dict, help_text='Additional certificate-specific data'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is REJECTED', null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certificate_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_templates/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='notes',
            field=models.JSONField(default=dict, help_text='Additional request-specific data'),
        ),
    ]
