# Generated by Django 5.0 on 2025-06-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterequest',
            old_name='notes',
            new_name='note',
        ),
    ]
