# Generated by Django 5.0 on 2025-06-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_rename_notes_certificaterequest_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterequest',
            old_name='note',
            new_name='notes',
        ),
    ]
