# Generated by Django 5.0 on 2025-06-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_rename_note_certificaterequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note from the approver', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetemplate'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
