# Generated by Django 5.0 on 2025-06-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificatetemplate_note_alter_certificate_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='reviewed_by',
        ),
    ]
