# Generated by Django 5.0 on 2025-07-03 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_remove_certificaterequest_reviewed_by'),
        ('events', '0005_remove_eventregistration_status_and_more'),
        ('knowledge_paths', '0003_alter_knowledgepath_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Additional notes from the certificate issuer'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Generated certificate file (PDF, etc.)', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event for which this certificate was issued', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='event_registration',
            field=models.ForeignKey(blank=True, help_text='Event registration associated with this certificate', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued the certificate (usually event creator or knowledge path author)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event for which certificate is requested', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'event'), ('user', 'knowledge_path')},
        ),
        migrations.AlterUniqueTogether(
            name='certificaterequest',
            unique_together={('requester', 'event'), ('requester', 'knowledge_path')},
        ),
    ]
