# Generated by Django 5.0 on 2025-02-20 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('VIDEO_CONSULTATION', 'Video Consultation'), ('CONTENT_CREATION', 'Content Creation')], max_length=20)),
                ('description', models.TextField()),
                ('knowledge_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='knowledge_paths.knowledgepath')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('knowledge_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='knowledge_paths.knowledgepath')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('knowledge_path', 'order')},
            },
        ),
        migrations.CreateModel(
            name='NodeActivityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('activity_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_paths.activityrequirement')),
                ('following_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceding_activities', to='knowledge_paths.node')),
                ('preceding_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_activities', to='knowledge_paths.node')),
            ],
            options={
                'unique_together': {('preceding_node', 'following_node', 'activity_requirement')},
            },
        ),
    ]
