# Generated by Django 5.0 on 2025-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepath',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Whether this knowledge path is visible to other users'),
        ),
    ]
