# Generated by Django 5.0 on 2025-02-20 23:00

import knowledge_paths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepath',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the knowledge path', null=True, upload_to=knowledge_paths.models.upload_knowledge_path_image),
        ),
    ]
