# Generated by Django 5.0 on 2025-02-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_content_activity_requirement'),
        ('knowledge_paths', '0001_initial'),
        ('profiles', '0003_alter_userprogressknowledgepath_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('knowledge_path', 'order')},
        ),
        migrations.AddField(
            model_name='node',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content'),
        ),
        migrations.AlterField(
            model_name='node',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=20),
        ),
        migrations.DeleteModel(
            name='NodeOrder',
        ),
        migrations.RemoveField(
            model_name='node',
            name='description',
        ),
    ]
