# Generated by Django 5.0 on 2025-07-01 22:09

import knowledge_paths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0002_knowledgepath_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepath',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the knowledge path', max_length=255, null=True, upload_to=knowledge_paths.models.upload_knowledge_path_image),
        ),
    ]
