# Generated by Django 5.0 on 2025-02-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0003_node_description'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='activityrequirement',
        #     name='knowledge_path',
        # ),
        # migrations.RemoveField(
        #     model_name='nodeactivityrequirement',
        #     name='activity_requirement',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='nodeactivityrequirement',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='nodeactivityrequirement',
        #     name='following_node',
        # ),
        # migrations.RemoveField(
        #     model_name='nodeactivityrequirement',
        #     name='preceding_node',
        # ),
    ]
