# Generated by Django 5.0 on 2025-02-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0004_remove_activityrequirement_knowledge_path_and_more'),
        ('profiles', '0005_remove_useractivitystatus_activity_requirement'),
        ('quizzes', '0002_remove_quiz_activity_requirement_quiz_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityRequirement',
        ),
        migrations.DeleteModel(
            name='NodeActivityRequirement',
        ),
    ]
