# Generated by Django 5.0 on 2026-07-22 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0004_knowledgepath_certificates_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepath',
            name='reference_price',
            field=models.FloatField(blank=True, default=0, help_text='Price in USD. 0 or null means the path is free.', null=True),
        ),
        migrations.CreateModel(
            name='KnowledgePathPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('price_amount', models.FloatField(help_text='USD price snapshot at purchase time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='knowledge_paths.knowledgepath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_path_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'knowledge_path')},
            },
        ),
    ]
