# Generated by Django 5.0 on 2025-03-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0005_delete_activityrequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgepath',
            name='votes',
        ),
    ]
