# Generated by Django 5.0 on 2025-04-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_publication_deleted'),
        ('knowledge_paths', '0006_remove_knowledgepath_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='content',
        ),
        migrations.AddField(
            model_name='node',
            name='content_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.contentprofile'),
        ),
    ]
