# Generated by Django 5.0 on 2026-09-23 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0007_rename_bch_direct_enabled_to_sales_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedKnowledgePathSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.CharField(max_length=64)),
                ('document_text', models.TextField(help_text='Exact JCS canonical JSON UTF-8 text that was hashed.')),
                ('digest', models.CharField(help_text='SHA-256 hex digest of document_text UTF-8 bytes.', max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_snapshots', to='knowledge_paths.knowledgepath')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_knowledge_path_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['digest'], name='kp_snapshot_digest_idx')],
                'unique_together': {('knowledge_path', 'version')},
            },
        ),
    ]
