# Generated by Django 5.0 on 2026-09-30 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_paths', '0008_published_knowledge_path_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePathSnapshotAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(help_text='SHA-256 hex digest copied from the published snapshot at anchor time.', max_length=64)),
                ('op_return_prefix', models.CharField(default='ACBC2', help_text='ASCII prefix prepended to digest bytes in the Bitcoin OP_RETURN.', max_length=16)),
                ('btc_network', models.CharField(choices=[('mainnet', 'Bitcoin mainnet'), ('testnet', 'Bitcoin testnet'), ('signet', 'Bitcoin signet'), ('regtest', 'Bitcoin regtest')], default='signet', max_length=16)),
                ('btc_txid', models.CharField(blank=True, help_text='Bitcoin transaction id (64 hex chars) once broadcast.', max_length=64)),
                ('btc_op_return_hex', models.CharField(blank=True, help_text='Hex payload pushed in OP_RETURN (prefix ASCII bytes + 32-byte digest).', max_length=256)),
                ('btc_block_height', models.PositiveIntegerField(blank=True, null=True)),
                ('btc_block_hash', models.CharField(blank=True, max_length=64)),
                ('btc_confirmations', models.PositiveIntegerField(default=0)),
                ('btc_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('btc_broadcast', 'Bitcoin broadcast'), ('anchored', 'Anchored on Bitcoin'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible extras (explorer URLs, raw receipts, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_path_snapshot_anchors', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_anchor', to='knowledge_paths.publishedknowledgepathsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['digest'], name='kp_snap_anchor_digest_idx'), models.Index(fields=['btc_txid'], name='kp_snap_anchor_btc_idx'), models.Index(fields=['status', 'created_at'], name='kp_snap_anchor_status_idx')],
            },
        ),
    ]
