# Generated by Django 5.0 on 2025-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, help_text='URL for external content', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='url_metadata',
            field=models.JSONField(blank=True, help_text='Metadata for URL content (platform, thumbnails, etc.)', null=True),
        ),
    ]
