# Generated by Django 5.0 on 2025-02-07 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='author',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='content',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='content',
            name='created_for',
        ),
        migrations.RemoveField(
            model_name='content',
            name='description',
        ),
        migrations.RemoveField(
            model_name='content',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='content',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.CreateModel(
            name='ContentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_note', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.collection')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='content.content')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
