# Generated by Django 5.0 on 2025-04-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='content',
        ),
        migrations.AddField(
            model_name='publication',
            name='content_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='content.contentprofile'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20),
        ),
    ]
