# Generated by Django 3.0.4 on 2024-05-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20240506_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Library'),
        ),
    ]
