# Generated by Django 5.0 on 2025-06-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_url_content_url_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='url_metadata',
        ),
        migrations.AddField(
            model_name='filedetails',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='og_image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='og_site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='og_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
