# Generated by Django 3.0.4 on 2024-05-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_file_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
