# Generated by Django 5.0 on 2025-02-13 23:11

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_topic_created_at_topic_topic_image_topic_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=content.models.topic_image_path),
        ),
    ]
