# Generated by Django 5.0 on 2025-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_publication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
