# Generated by Django 5.0 on 2026-03-26 21:54

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_profile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=content.models.content_file_upload_path),
        ),
    ]
