# Generated by Django 3.0.4 on 2024-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_file_ai_detection_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
