# Generated by Django 5.0 on 2025-02-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_knowledge_path_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='activity_requirement',
        ),
    ]
