# Generated by Django 5.0 on 2026-03-27 02:36

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_filesuggestion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='filesuggestion',
            new_name='content_fil_content_32a911_idx',
            old_name='content_file_content_58ff3f_idx',
        ),
        migrations.RenameIndex(
            model_name='filesuggestion',
            new_name='content_fil_suggest_bb8121_idx',
            old_name='content_file_suggeste_6de376_idx',
        ),
        migrations.AlterField(
            model_name='contentprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=content.models.content_profile_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='filesuggestion',
            name='file',
            field=models.FileField(upload_to=content.models.file_suggestion_upload_path),
        ),
    ]
