# Generated by Django 5.0 on 2026-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_filedetails_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When true, authenticated users can discover this collection and view visible items.'),
        ),
    ]
