# Generated by Django 5.0 on 2026-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_topictimelineentrycontentsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(
                default=True,
                help_text='When false, the topic is hidden from public listings and search.',
            ),
        ),
    ]
