# Generated by Django 5.0 on 2026-07-28 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_contentprofile_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccreationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='TranscriptAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(help_text='SHA-256 hex digest snapshot (same algorithm as ContentTranscript.text_hash).', max_length=64)),
                ('text_length', models.PositiveIntegerField(blank=True, help_text='Length of normalized hash-source text at certify time.', null=True)),
                ('op_return_prefix', models.CharField(default='ACBC1', help_text='ASCII prefix prepended to text_hash bytes in the Bitcoin OP_RETURN.', max_length=16)),
                ('btc_network', models.CharField(choices=[('mainnet', 'Bitcoin mainnet'), ('testnet', 'Bitcoin testnet'), ('signet', 'Bitcoin signet'), ('regtest', 'Bitcoin regtest')], default='testnet', max_length=16)),
                ('btc_txid', models.CharField(blank=True, help_text='Bitcoin transaction id (64 hex chars) once broadcast.', max_length=64)),
                ('btc_op_return_hex', models.CharField(blank=True, help_text='Hex payload pushed in OP_RETURN (prefix ASCII bytes + 32-byte digest).', max_length=256)),
                ('btc_block_height', models.PositiveIntegerField(blank=True, null=True)),
                ('btc_block_hash', models.CharField(blank=True, max_length=64)),
                ('btc_confirmations', models.PositiveIntegerField(default=0)),
                ('btc_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('evm_chain_id', models.PositiveIntegerField(blank=True, help_text='EVM chain id (e.g. 80002 Amoy, 137 Polygon).', null=True)),
                ('evm_contract_address', models.CharField(blank=True, max_length=42)),
                ('evm_tx_hash', models.CharField(blank=True, help_text='0x-prefixed EVM transaction hash.', max_length=66)),
                ('evm_block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('evm_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('ipfs_cid', models.CharField(blank=True, help_text='IPFS CID for the certified plain text, if pinned.', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('btc_broadcast', 'Bitcoin broadcast'), ('btc_confirmed', 'Bitcoin confirmed'), ('evm_broadcast', 'EVM broadcast'), ('anchored', 'Anchored'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible extras (explorer URLs, raw receipts, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_anchors', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_anchors', to='content.content')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['text_hash'], name='transcript_anchor_hash_idx'), models.Index(fields=['btc_txid'], name='transcript_anchor_btc_idx'), models.Index(fields=['status', 'created_at'], name='transcript_anchor_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transcriptanchor',
            constraint=models.UniqueConstraint(fields=('content', 'text_hash'), name='unique_transcript_anchor_content_hash'),
        ),
    ]
