# Generated by Django 5.0 on 2026-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_transcript_anchor_bitcoin_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptanchor',
            name='btc_network',
            field=models.CharField(choices=[('mainnet', 'Bitcoin mainnet'), ('testnet', 'Bitcoin testnet'), ('signet', 'Bitcoin signet'), ('regtest', 'Bitcoin regtest')], default='signet', max_length=16),
        ),
    ]
