# Generated by Django 5.0 on 2026-07-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_transcript_anchor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptanchor',
            name='evm_block_number',
        ),
        migrations.RemoveField(
            model_name='transcriptanchor',
            name='evm_chain_id',
        ),
        migrations.RemoveField(
            model_name='transcriptanchor',
            name='evm_contract_address',
        ),
        migrations.RemoveField(
            model_name='transcriptanchor',
            name='evm_recorded_at',
        ),
        migrations.RemoveField(
            model_name='transcriptanchor',
            name='evm_tx_hash',
        ),
        migrations.AlterField(
            model_name='transcriptanchor',
            name='ipfs_cid',
            field=models.CharField(blank=True, help_text='Optional IPFS CID for the certified plain text (off-chain pointer only).', max_length=128),
        ),
        migrations.AlterField(
            model_name='transcriptanchor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('btc_broadcast', 'Bitcoin broadcast'), ('anchored', 'Anchored on Bitcoin'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
