# Generated by Django 5.0 on 2026-09-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_transcript_anchor_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='chat_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo y el tema tiene transcripciones indexadas, los usuarios ven la pestaña Conversar.', verbose_name='Conversar'),
        ),
    ]
