# Generated by Django 5.0 on 2026-09-01 22:23

import utils.db_encoding
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_transcript_anchor_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicchatquery',
            name='sources',
            field=utils.db_encoding.TextJSONField(
                blank=True,
                default=list,
                help_text='Citation payloads returned with the answer (index, content_id, excerpt, …).',
            ),
        ),
    ]
