# Generated by Django 5.0 on 2026-09-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_topicchatquery_sources_text_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='chat_enabled',
            field=models.BooleanField(default=False, help_text='When true, the Consultas (RAG consultations) tab is visible on the topic page.'),
        ),
    ]
