# Generated by Django 5.0 on 2026-09-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_topicchatquery_chunk_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicchatquery',
            name='selected_content_ids',
            field=models.JSONField(blank=True, default=list, help_text='Content IDs the user chose for this consultation. Empty means all indexed transcripts in the topic were eligible.'),
        ),
    ]
