# Generated by Django 5.0 on 2026-09-02 23:59

import django.db.models.deletion
from django.db import migrations, models


def copy_transcript_embeddings_to_content_embedding(apps, schema_editor):
    """
    Existing rows: copy ContentTranscript.embedding_* into ContentEmbedding
    for the same Content. No Qdrant re-index.
    """
    ContentTranscript = apps.get_model('content', 'ContentTranscript')
    ContentEmbedding = apps.get_model('content', 'ContentEmbedding')

    batch = []
    for transcript in ContentTranscript.objects.all().iterator(chunk_size=500):
        batch.append(
            ContentEmbedding(
                content_id=transcript.content_id,
                status=transcript.embedding_status or 'pending',
                model=transcript.embedding_model or '',
                dims=transcript.embedding_dims,
                chunk_count=transcript.chunk_count,
                source_hash=transcript.embedded_text_hash,
                embedded_at=transcript.embedded_at,
                error=transcript.embedding_error or '',
            )
        )
        if len(batch) >= 500:
            ContentEmbedding.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []
    if batch:
        ContentEmbedding.objects.bulk_create(batch, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    # Forward copy is lossy for reverse (would need to write back onto transcripts).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_topicchatquery_selected_content_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('indexed', 'Indexed'),
                            ('stale', 'Stale'),
                            ('failed', 'Failed'),
                            ('skipped', 'Skipped'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Whether current source_hash is indexed in the external vector DB.',
                        max_length=16,
                    ),
                ),
                (
                    'model',
                    models.CharField(
                        blank=True,
                        help_text='Embedding model last used when status=indexed (set by embed worker ack).',
                        max_length=64,
                    ),
                ),
                (
                    'dims',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text='Vector dimensions for model.',
                        null=True,
                    ),
                ),
                (
                    'chunk_count',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Number of chunks upserted to the vector DB on last successful index.',
                        null=True,
                    ),
                ),
                (
                    'source_hash',
                    models.CharField(
                        blank=True,
                        help_text=(
                            'Hash of the source that was indexed (transcript text_hash for A/V, '
                            'or worker-supplied file/content hash for TEXT).'
                        ),
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    'embedded_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='When the vector DB was last successfully updated for this content.',
                        null=True,
                    ),
                ),
                (
                    'error',
                    models.TextField(
                        blank=True,
                        help_text='Last embed-worker error message when status=failed.',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'content',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='embedding',
                        to='content.content',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='contentembedding',
            index=models.Index(fields=['source_hash'], name='content_emb_source_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='contentembedding',
            index=models.Index(fields=['status'], name='content_emb_status_idx'),
        ),
        migrations.RunPython(copy_transcript_embeddings_to_content_embedding, noop_reverse),
        migrations.RemoveIndex(
            model_name='contenttranscript',
            name='content_tr_emb_hash_idx',
        ),
        migrations.RemoveField(
            model_name='contenttranscript',
            name='chunk_count',
        ),
        migrations.RemoveField(
            model_name='contenttranscript',
            name='embedded_at',
        ),
        migrations.RemoveField(
            model_name='contenttranscript',
            name='embedded_text_hash',
        ),
        migrations.RemoveField(
            model_name='contenttranscript',
            name='embedding_dims',
        ),
        migrations.RemoveField(
            model_name='contenttranscript',
            name='embedding_error',
        ),
        migrations.RemoveField(
            model_name='contenttranscript',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='contenttranscript',
            name='embedding_status',
        ),
    ]
