# Generated by Django 5.0 on 2026-09-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_rename_topic_bch_direct_enabled_to_sales_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptanchor',
            name='certified_plain_text',
            field=models.TextField(
                blank=True,
                help_text=(
                    'Exact normalized plain text whose SHA-256 is text_hash '
                    '(snapshot at certify time for public verification).'
                ),
            ),
        ),
    ]
