# Generated by Django 5.0 on 2026-09-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_transcript_anchor_certified_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttranscript',
            name='format',
            field=models.CharField(choices=[('SRT', 'SubRip (.srt)'), ('VTT', 'WebVTT (.vtt)'), ('PLAIN', 'Plain text extract (PDF/TEXT)')], default='SRT', max_length=5),
        ),
        migrations.AlterField(
            model_name='contenttranscript',
            name='processed_plain',
            field=models.TextField(blank=True, help_text='spaCy-cleaned or PDF-extracted plain text; primary source for hash, snapshots, and RAG.'),
        ),
        migrations.AlterField(
            model_name='contenttranscript',
            name='source_subtitles',
            field=models.TextField(blank=True, help_text='Optional raw SRT/VTT in memory for timed segments (A/V; not required for TEXT).'),
        ),
        migrations.AlterField(
            model_name='contentembedding',
            name='source_hash',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Hash of the source that was indexed '
                    '(ContentTranscript.text_hash for VIDEO/AUDIO/TEXT).'
                ),
                max_length=64,
                null=True,
            ),
        ),
    ]
