# Generated by Django 5.0 on 2026-10-01 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_contenttranscript_external_text_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlimitedConsultationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_unlimited_consultation_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User ID that may create unlimited topic consultations per day.', on_delete=django.db.models.deletion.CASCADE, related_name='unlimited_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unlimited consultation user',
                'verbose_name_plural': 'unlimited consultation users',
                'ordering': ['-created_at'],
            },
        ),
    ]
