# Generated by Django 5.0 on 2025-05-20 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'content_type', 'object_id', 'topic')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['topic'], name='votes_vote_topic_i_590796_idx'),
        ),
        migrations.AddIndex(
            model_name='votecount',
            index=models.Index(fields=['topic'], name='votes_votec_topic_i_0dbfb2_idx'),
        ),
    ]
