# Generated by Django 5.0 on 2025-03-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_vote_topic_votecount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentVoteTopicCount',
        ),
    ]
