# Generated by Django 5.0 on 2025-02-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('knowledge_paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcall',
            name='activity_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_calls', to='knowledge_paths.activityrequirement'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='activity_requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='knowledge_paths.activityrequirement'),
        ),
    ]
