# Generated by Django 5.0 on 2025-07-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(blank=True, choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('facebook', 'Facebook Gaming'), ('mixer', 'Mixer'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
