# Generated by Django 5.0 on 2025-07-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_platform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionPlatform',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_recurrent',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('LIVE_COURSE', 'Live Course'), ('LIVE_CERTIFICATION', 'Live Certification'), ('LIVE_MASTER_CLASS', 'Live Master Class')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
