from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    PublicationListView,
    PublicationDetailView,
    LibraryListView,
    LibraryDetailView,
    UserCollectionsView,
    CollectionDetailView,
    CollectionContentView,
    ContentDetailView,
    ContentUpdateView,
    ContentModificationCheckView,
    ContentPreviewView,
    KnowledgePathListView,
    KnowledgePathDetailView,
    KnowledgePathNodesView,
    NodeDetailView,
    TopicView,
    TopicDetailView,
    TopicContentSimpleView,
    TopicBasicView,
    UploadContentView,
    UserContentListView,
    UserContentWithDetailsView,
    ContentProfileView,
    TopicEditContentView,
    TopicModeratorsView,
    TopicModeratorInviteView,
    TopicModeratorInvitationsView,
    TopicModeratorAcceptView,
    TopicModeratorDeclineView,
    TopicContentMediaTypeView,
    UserTopicsView,
    UserTopicInvitationsView,
    RecentUserContentView,
    UserContentByIdView,
    ContentReferencesView,
    ContentProfileDetailView,
    ContentProfileCreateView,
    URLPreviewView,
    TopicContentSuggestionCreateView,
    TopicContentSuggestionsView,
    TopicContentSuggestionAcceptView,
    TopicContentSuggestionRejectView,
    TopicContentSuggestionDeleteView,
    UserContentSuggestionsView
)

app_name = "content"

urlpatterns = [
    # Publication URLs
    path('publications/', PublicationListView.as_view(), name='publication-list'),
    path('publications/<int:pk>/', PublicationDetailView.as_view(), name='publication-detail'),
    path('publications/user/<int:user_id>/', PublicationListView.as_view(), name='user-publications'),
    
    # Existing URLs
    path('libraries/', LibraryListView.as_view(), name='library_list'),
    path('libraries/<int:pk>/', LibraryDetailView.as_view(), name='library_detail'),
    path('collections/', UserCollectionsView.as_view(), name='user-collections'),
    path('collections/<int:collection_id>/', CollectionDetailView.as_view(), name='collection-detail'),
    path('collections/<int:collection_id>/content/', CollectionContentView.as_view(), name='collection-content'),
    path('content_details/<int:pk>/', ContentDetailView.as_view(), name='content-detail'),
    path('content_update/<int:pk>/', ContentUpdateView.as_view(), name='content-update'),
    path('content_modification_check/<int:pk>/', ContentModificationCheckView.as_view(), name='content-modification-check'),
    path('content_preview/<int:pk>/', ContentPreviewView.as_view(), name='content-preview'),
    path('knowledge-paths/', KnowledgePathListView.as_view(), name='knowledge_path_list'),
    path('knowledge-paths/<int:pk>/', KnowledgePathDetailView.as_view(), name='knowledge_path_detail'),
    path('knowledge-paths/<int:pk>/nodes/', KnowledgePathNodesView.as_view(), name='knowledge_path_nodes'),
    path('nodes/<int:pk>/', NodeDetailView.as_view(), name='node_detail'),
    path('topics/', TopicView.as_view(), name='topics'),
    path('topics/<int:pk>/', TopicDetailView.as_view(), name='topic-detail'),
    path('topics/<int:pk>/content-simple/', TopicContentSimpleView.as_view(), name='topic-content-simple'),
    path('topics/<int:pk>/basic/', TopicBasicView.as_view(), name='topic-basic'),
    path('upload-content/', UploadContentView.as_view(), name='upload_content'),
    path('user-content/', UserContentListView.as_view(), name='user-content'),
    path('user-content-with-details/', UserContentWithDetailsView.as_view(), name='user-content-with-details'),
    path('user-content/<int:user_id>/', UserContentByIdView.as_view(), name='user-content-by-id'),
    path('content-profiles/', ContentProfileCreateView.as_view(), name='content-profile-create'),
    path('content-profiles/<int:content_profile_id>/', ContentProfileView.as_view(), name='content-profile-view'),
    path('content-profiles/<int:profile_id>/detail/', ContentProfileDetailView.as_view(), name='content-profile-detail'),
    path('topics/<int:pk>/content/', TopicEditContentView.as_view(), name='topic-edit-content'),
    path('topics/<int:pk>/moderators/', TopicModeratorsView.as_view(), name='topic-moderators'),
    path('topics/<int:pk>/moderators/invite/', TopicModeratorInviteView.as_view(), name='topic-moderator-invite'),
    path('topics/<int:pk>/moderators/invitations/', TopicModeratorInvitationsView.as_view(), name='topic-moderator-invitations'),
    path('topics/<int:pk>/moderators/invitations/<int:invitation_id>/accept/', TopicModeratorAcceptView.as_view(), name='topic-moderator-accept'),
    path('topics/<int:pk>/moderators/invitations/<int:invitation_id>/decline/', TopicModeratorDeclineView.as_view(), name='topic-moderator-decline'),
    path('topics/<int:pk>/content/<str:media_type>/', TopicContentMediaTypeView.as_view(), name='topic-content-media-type'),
    path('user/topics/', UserTopicsView.as_view(), name='user-topics'),
    path('user/topics/invitations/', UserTopicInvitationsView.as_view(), name='user-topic-invitations'),
    path('topics/<int:pk>/content-suggestions/', TopicContentSuggestionsView.as_view(), name='topic-content-suggestions'),
    path('topics/<int:pk>/content-suggestions/create/', TopicContentSuggestionCreateView.as_view(), name='topic-content-suggestion-create'),
    path('topics/<int:pk>/content-suggestions/<int:suggestion_id>/accept/', TopicContentSuggestionAcceptView.as_view(), name='topic-content-suggestion-accept'),
    path('topics/<int:pk>/content-suggestions/<int:suggestion_id>/reject/', TopicContentSuggestionRejectView.as_view(), name='topic-content-suggestion-reject'),
    path('topics/<int:pk>/content-suggestions/<int:suggestion_id>/', TopicContentSuggestionDeleteView.as_view(), name='topic-content-suggestion-delete'),
    path('user/content-suggestions/', UserContentSuggestionsView.as_view(), name='user-content-suggestions'),
    path('recent-user-content/', RecentUserContentView.as_view(), name='recent-user-content'),
    path('references/<int:pk>/', ContentReferencesView.as_view(), name='content-references'),
    path('preview-url/', URLPreviewView.as_view(), name='preview-url'),
]
