from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    PublicationListView,
    PublicationDetailView,
    LibraryListView,
    LibraryDetailView,
    UserCollectionsView,
    PublicCollectionsView,
    CollectionDetailView,
    CollectionContentView,
    ContentDetailView,
    ContentUpdateView,
    ContentModificationCheckView,
    ContentPreviewView,
    KnowledgePathListView,
    KnowledgePathDetailView,
    KnowledgePathNodesView,
    NodeDetailView,
    TopicView,
    TopicDetailView,
    TopicContentSimpleView,
    TopicBasicView,
    UploadContentView,
    UploadContentPresignView,
    UploadContentConfirmView,
    UserContentListView,
    UserContentWithDetailsView,
    ContentProfileView,
    TopicEditContentView,
    TopicModeratorsView,
    UserSearchView,
    TopicModeratorInviteView,
    TopicModeratorInvitationsView,
    TopicModeratorAcceptView,
    TopicModeratorDeclineView,
    TopicContentMediaTypeView,
    TopicTimelineView,
    TopicTimelineEntryDetailView,
    TopicTimelineReorderView,
    UserTopicsView,
    UserTopicInvitationsView,
    RecentUserContentView,
    UserContentByIdView,
    ContentReferencesView,
    ContentProfileDetailView,
    ContentProfileCreateView,
    URLPreviewView,
    TopicContentSuggestionCreateView,
    TopicContentSuggestionsView,
    TopicContentSuggestionAcceptView,
    TopicContentSuggestionRejectView,
    TopicContentSuggestionDeleteView,
    UserContentSuggestionsView,
    TopicTimelineEntrySuggestionCreateView,
    TopicTimelineEntrySuggestionsView,
    TopicTimelineEntrySuggestionAcceptView,
    TopicTimelineEntrySuggestionRejectView,
    TopicTimelineEntrySuggestionDeleteView,
    UserTimelineEntrySuggestionsView,
    TopicTimelineEntryContentSuggestionCreateView,
    TopicTimelineEntryContentSuggestionsView,
    TopicTimelineEntryContentSuggestionAcceptView,
    TopicTimelineEntryContentSuggestionRejectView,
    TopicTimelineEntryContentSuggestionDeleteView,
    UserTimelineEntryContentSuggestionsView,
    FileSuggestionCreateView,
    ContentOwnerAttachPresignView,
    ContentOwnerAttachConfirmView,
    ContentOwnerAttachView,
    FileSuggestionPresignView,
    FileSuggestionConfirmView,
    FileSuggestionListView,
    FileSuggestionAcceptView,
    FileSuggestionRejectView
)
from .views_youtube_migration import YouTubeMigrationManifestView
from .views_transcript_ingest import (
    ContentTranscriptIngestQueueView,
    ContentTranscriptIngestDetailView,
)

app_name = "content"

urlpatterns = [
    # Publication URLs
    path('publications/', PublicationListView.as_view(), name='publication-list'),
    path('publications/<int:pk>/', PublicationDetailView.as_view(), name='publication-detail'),
    path('publications/user/<int:user_id>/', PublicationListView.as_view(), name='user-publications'),
    
    # Existing URLs
    path('libraries/', LibraryListView.as_view(), name='library_list'),
    path('libraries/<int:pk>/', LibraryDetailView.as_view(), name='library_detail'),
    path('collections/', UserCollectionsView.as_view(), name='user-collections'),
    path('collections/public/', PublicCollectionsView.as_view(), name='public-collections'),
    path('collections/<int:collection_id>/', CollectionDetailView.as_view(), name='collection-detail'),
    path('collections/<int:collection_id>/content/', CollectionContentView.as_view(), name='collection-content'),
    path('content_details/<int:pk>/', ContentDetailView.as_view(), name='content-detail'),
    path('content_update/<int:pk>/', ContentUpdateView.as_view(), name='content-update'),
    path('content_modification_check/<int:pk>/', ContentModificationCheckView.as_view(), name='content-modification-check'),
    path('content_preview/<int:pk>/', ContentPreviewView.as_view(), name='content-preview'),
    path('knowledge-paths/', KnowledgePathListView.as_view(), name='knowledge_path_list'),
    path('knowledge-paths/<int:pk>/', KnowledgePathDetailView.as_view(), name='knowledge_path_detail'),
    path('knowledge-paths/<int:pk>/nodes/', KnowledgePathNodesView.as_view(), name='knowledge_path_nodes'),
    path('nodes/<int:pk>/', NodeDetailView.as_view(), name='node_detail'),
    path('topics/', TopicView.as_view(), name='topics'),
    path('topics/<int:pk>/', TopicDetailView.as_view(), name='topic-detail'),
    path('topics/<int:pk>/content-simple/', TopicContentSimpleView.as_view(), name='topic-content-simple'),
    path('topics/<int:pk>/basic/', TopicBasicView.as_view(), name='topic-basic'),
    path('topics/<int:pk>/timeline/', TopicTimelineView.as_view(), name='topic-timeline'),
    path('topics/<int:pk>/timeline/reorder/', TopicTimelineReorderView.as_view(), name='topic-timeline-reorder'),
    path('topics/<int:pk>/timeline/<int:entry_id>/', TopicTimelineEntryDetailView.as_view(), name='topic-timeline-entry-detail'),
    path('upload-content/', UploadContentView.as_view(), name='upload_content'),
    path('upload-content/presign/', UploadContentPresignView.as_view(), name='upload_content_presign'),
    path('upload-content/confirm/', UploadContentConfirmView.as_view(), name='upload_content_confirm'),
    path('user-content/', UserContentListView.as_view(), name='user-content'),
    path('user-content-with-details/', UserContentWithDetailsView.as_view(), name='user-content-with-details'),
    path('user-content/<int:user_id>/', UserContentByIdView.as_view(), name='user-content-by-id'),
    path('content-profiles/', ContentProfileCreateView.as_view(), name='content-profile-create'),
    path('content-profiles/<int:content_profile_id>/', ContentProfileView.as_view(), name='content-profile-view'),
    path('content-profiles/<int:profile_id>/detail/', ContentProfileDetailView.as_view(), name='content-profile-detail'),
    path('topics/<int:pk>/content/', TopicEditContentView.as_view(), name='topic-edit-content'),
    path('users/search/', UserSearchView.as_view(), name='user-search'),
    path('topics/<int:pk>/moderators/', TopicModeratorsView.as_view(), name='topic-moderators'),
    path('topics/<int:pk>/moderators/invite/', TopicModeratorInviteView.as_view(), name='topic-moderator-invite'),
    path('topics/<int:pk>/moderators/invitations/', TopicModeratorInvitationsView.as_view(), name='topic-moderator-invitations'),
    path('topics/<int:pk>/moderators/invitations/<int:invitation_id>/accept/', TopicModeratorAcceptView.as_view(), name='topic-moderator-accept'),
    path('topics/<int:pk>/moderators/invitations/<int:invitation_id>/decline/', TopicModeratorDeclineView.as_view(), name='topic-moderator-decline'),
    path('topics/<int:pk>/content/<str:media_type>/', TopicContentMediaTypeView.as_view(), name='topic-content-media-type'),
    path('user/topics/', UserTopicsView.as_view(), name='user-topics'),
    path('user/topics/invitations/', UserTopicInvitationsView.as_view(), name='user-topic-invitations'),
    path('topics/<int:pk>/content-suggestions/', TopicContentSuggestionsView.as_view(), name='topic-content-suggestions'),
    path('topics/<int:pk>/content-suggestions/create/', TopicContentSuggestionCreateView.as_view(), name='topic-content-suggestion-create'),
    path('topics/<int:pk>/content-suggestions/<int:suggestion_id>/accept/', TopicContentSuggestionAcceptView.as_view(), name='topic-content-suggestion-accept'),
    path('topics/<int:pk>/content-suggestions/<int:suggestion_id>/reject/', TopicContentSuggestionRejectView.as_view(), name='topic-content-suggestion-reject'),
    path('topics/<int:pk>/content-suggestions/<int:suggestion_id>/', TopicContentSuggestionDeleteView.as_view(), name='topic-content-suggestion-delete'),
    path('user/content-suggestions/', UserContentSuggestionsView.as_view(), name='user-content-suggestions'),
    path('topics/<int:pk>/timeline-suggestions/create/', TopicTimelineEntrySuggestionCreateView.as_view(), name='topic-timeline-suggestion-create'),
    path('topics/<int:pk>/timeline-suggestions/', TopicTimelineEntrySuggestionsView.as_view(), name='topic-timeline-suggestions'),
    path('topics/<int:pk>/timeline-suggestions/<int:suggestion_id>/accept/', TopicTimelineEntrySuggestionAcceptView.as_view(), name='topic-timeline-suggestion-accept'),
    path('topics/<int:pk>/timeline-suggestions/<int:suggestion_id>/reject/', TopicTimelineEntrySuggestionRejectView.as_view(), name='topic-timeline-suggestion-reject'),
    path('topics/<int:pk>/timeline-suggestions/<int:suggestion_id>/', TopicTimelineEntrySuggestionDeleteView.as_view(), name='topic-timeline-suggestion-delete'),
    path('user/timeline-entry-suggestions/', UserTimelineEntrySuggestionsView.as_view(), name='user-timeline-entry-suggestions'),
    path('topics/<int:pk>/timeline/<int:entry_id>/content-suggestions/create/', TopicTimelineEntryContentSuggestionCreateView.as_view(), name='topic-timeline-entry-content-suggestion-create'),
    path('topics/<int:pk>/timeline-entry-content-suggestions/', TopicTimelineEntryContentSuggestionsView.as_view(), name='topic-timeline-entry-content-suggestions'),
    path('topics/<int:pk>/timeline-entry-content-suggestions/<int:suggestion_id>/accept/', TopicTimelineEntryContentSuggestionAcceptView.as_view(), name='topic-timeline-entry-content-suggestion-accept'),
    path('topics/<int:pk>/timeline-entry-content-suggestions/<int:suggestion_id>/reject/', TopicTimelineEntryContentSuggestionRejectView.as_view(), name='topic-timeline-entry-content-suggestion-reject'),
    path('topics/<int:pk>/timeline-entry-content-suggestions/<int:suggestion_id>/', TopicTimelineEntryContentSuggestionDeleteView.as_view(), name='topic-timeline-entry-content-suggestion-delete'),
    path('user/timeline-entry-content-suggestions/', UserTimelineEntryContentSuggestionsView.as_view(), name='user-timeline-entry-content-suggestions'),
    path('content/<int:pk>/owner-attach/presign/', ContentOwnerAttachPresignView.as_view(), name='content-owner-attach-presign'),
    path('content/<int:pk>/owner-attach/confirm/', ContentOwnerAttachConfirmView.as_view(), name='content-owner-attach-confirm'),
    path('content/<int:pk>/owner-attach/', ContentOwnerAttachView.as_view(), name='content-owner-attach'),
    path('content/<int:pk>/file-suggestions/presign/', FileSuggestionPresignView.as_view(), name='file-suggestion-presign'),
    path('content/<int:pk>/file-suggestions/confirm/', FileSuggestionConfirmView.as_view(), name='file-suggestion-confirm'),
    path('content/<int:pk>/file-suggestions/', FileSuggestionCreateView.as_view(), name='file-suggestion-create'),
    path('content/<int:pk>/file-suggestions/list/', FileSuggestionListView.as_view(), name='file-suggestion-list'),
    path('file-suggestions/<int:suggestion_id>/accept/', FileSuggestionAcceptView.as_view(), name='file-suggestion-accept'),
    path('file-suggestions/<int:suggestion_id>/reject/', FileSuggestionRejectView.as_view(), name='file-suggestion-reject'),
    path('recent-user-content/', RecentUserContentView.as_view(), name='recent-user-content'),
    path('references/<int:pk>/', ContentReferencesView.as_view(), name='content-references'),
    path('preview-url/', URLPreviewView.as_view(), name='preview-url'),
    path(
        'youtube-migration-manifest/',
        YouTubeMigrationManifestView.as_view(),
        name='youtube-migration-manifest',
    ),
    path(
        'transcript-ingest/',
        ContentTranscriptIngestQueueView.as_view(),
        name='transcript-ingest-queue',
    ),
    path(
        'transcript-ingest/<int:content_id>/',
        ContentTranscriptIngestDetailView.as_view(),
        name='transcript-ingest-detail',
    ),
]
